import React from 'react';
import {
  AlarmClockIcon,
  AlertTriangleIcon,
  AnchorIcon,
  AwardIcon,
  BadgeCheckIcon,
  BanknoteIcon,
  BarChart3Icon,
  BellIcon,
  BookOpenIcon,
  BookmarkIcon,
  BriefcaseIcon,
  BuildingIcon,
  CalendarIcon,
  CameraIcon,
  CarIcon,
  CheckIcon,
  CircleCheckBigIcon,
  ClipboardListIcon,
  ClockIcon,
  CloudIcon,
  CodeIcon,
  CoffeeIcon,
  CompassIcon,
  CpuIcon,
  CreditCardIcon,
  CrownIcon,
  DatabaseIcon,
  DollarSignIcon,
  DownloadIcon,
  DumbbellIcon,
  EuroIcon,
  EyeIcon,
  FileTextIcon,
  FilmIcon,
  FlagIcon,
  FlameIcon,
  FolderIcon,
  GaugeIcon,
  GiftIcon,
  GlobeIcon,
  GraduationCapIcon,
  HandshakeIcon,
  HeadphonesIcon,
  HeartIcon,
  HomeIcon,
  ImageIcon,
  InboxIcon,
  InfoIcon,
  KeyIcon,
  LaptopIcon,
  LayersIcon,
  LeafIcon,
  LifeBuoyIcon,
  LightbulbIcon,
  LinkIcon,
  ListChecksIcon,
  LockIcon,
  MailIcon,
  MapPinIcon,
  MegaphoneIcon,
  MessageCircleIcon,
  MicIcon,
  MonitorIcon,
  MoonIcon,
  MousePointerClickIcon,
  MusicIcon,
  NewspaperIcon,
  PackageIcon,
  PaletteIcon,
  PaperclipIcon,
  PenToolIcon,
  PercentIcon,
  PhoneIcon,
  PieChartIcon,
  PlaneIcon,
  PlayIcon,
  PresentationIcon,
  PrinterIcon,
  RocketIcon,
  SearchIcon,
  SendIcon,
  SettingsIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  SmileIcon,
  SparklesIcon,
  StarIcon,
  SunIcon,
  TagIcon,
  TargetIcon,
  ThumbsUpIcon,
  TimerIcon,
  TrendingUpIcon,
  TrophyIcon,
  TruckIcon,
  UsersIcon,
  VideoIcon,
  WalletIcon,
  ZapIcon } from
'lucide-react';

type IconComponent = typeof StarIcon;

/** Biblioteca de iconițe disponibile pentru elementul Icon */
export const elementIconOptions: Array<{
  key: string;
  label: string;
  icon: IconComponent;
  /** Iconița se randează plină, nu doar cu contur */
  filled?: boolean;
}> = [
{ key: 'starFilled', label: 'Stea plină', icon: StarIcon, filled: true },
{ key: 'heartFilled', label: 'Inimă plină', icon: HeartIcon, filled: true },
{
  key: 'circleCheckFilled',
  label: 'Bifă în cerc plin',
  icon: CircleCheckBigIcon,
  filled: true
},
{
  key: 'badgeCheckFilled',
  label: 'Bifă cu contur plin',
  icon: BadgeCheckIcon,
  filled: true
},
{
  key: 'trophyFilled',
  label: 'Trofeu plin',
  icon: TrophyIcon,
  filled: true
},
{ key: 'shieldFilled', label: 'Scut plin', icon: ShieldCheckIcon, filled: true },
{ key: 'flameFilled', label: 'Flacără plină', icon: FlameIcon, filled: true },
{ key: 'zapFilled', label: 'Fulger plin', icon: ZapIcon, filled: true },
{ key: 'crownFilled', label: 'Coroană plină', icon: CrownIcon, filled: true },
{
  key: 'sparklesFilled',
  label: 'Sclipire plină',
  icon: SparklesIcon,
  filled: true
},
{ key: 'bulbFilled', label: 'Bec plin', icon: LightbulbIcon, filled: true },
{
  key: 'thumbsUpFilled',
  label: 'Like plin',
  icon: ThumbsUpIcon,
  filled: true
},
{ key: 'star', label: 'Stea', icon: StarIcon },
{ key: 'sparkles', label: 'Sclipire', icon: SparklesIcon },
{ key: 'heart', label: 'Inimă', icon: HeartIcon },
{ key: 'check', label: 'Bifă', icon: CheckIcon },
{ key: 'circleCheck', label: 'Bifă în cerc', icon: CircleCheckBigIcon },
{ key: 'badgeCheck', label: 'Bifă cu contur', icon: BadgeCheckIcon },
{ key: 'shield', label: 'Scut', icon: ShieldCheckIcon },
{ key: 'lock', label: 'Lacăt', icon: LockIcon },
{ key: 'key', label: 'Cheie', icon: KeyIcon },
{ key: 'trophy', label: 'Trofeu', icon: TrophyIcon },
{ key: 'award', label: 'Medalie', icon: AwardIcon },
{ key: 'crown', label: 'Coroană', icon: CrownIcon },
{ key: 'target', label: 'Țintă', icon: TargetIcon },
{ key: 'rocket', label: 'Rachetă', icon: RocketIcon },
{ key: 'zap', label: 'Fulger', icon: ZapIcon },
{ key: 'flame', label: 'Flacără', icon: FlameIcon },
{ key: 'bulb', label: 'Bec', icon: LightbulbIcon },
{ key: 'trending', label: 'Creștere', icon: TrendingUpIcon },
{ key: 'barChart', label: 'Grafic bare', icon: BarChart3Icon },
{ key: 'pieChart', label: 'Grafic circular', icon: PieChartIcon },
{ key: 'gauge', label: 'Indicator', icon: GaugeIcon },
{ key: 'percent', label: 'Procent', icon: PercentIcon },
{ key: 'dollar', label: 'Dolar', icon: DollarSignIcon },
{ key: 'euro', label: 'Euro', icon: EuroIcon },
{ key: 'banknote', label: 'Bancnotă', icon: BanknoteIcon },
{ key: 'wallet', label: 'Portofel', icon: WalletIcon },
{ key: 'creditCard', label: 'Card', icon: CreditCardIcon },
{ key: 'cart', label: 'Coș', icon: ShoppingCartIcon },
{ key: 'bag', label: 'Sacoșă', icon: ShoppingBagIcon },
{ key: 'tag', label: 'Etichetă', icon: TagIcon },
{ key: 'gift', label: 'Cadou', icon: GiftIcon },
{ key: 'package', label: 'Colet', icon: PackageIcon },
{ key: 'truck', label: 'Camion', icon: TruckIcon },
{ key: 'plane', label: 'Avion', icon: PlaneIcon },
{ key: 'car', label: 'Mașină', icon: CarIcon },
{ key: 'mapPin', label: 'Locație', icon: MapPinIcon },
{ key: 'globe', label: 'Glob', icon: GlobeIcon },
{ key: 'compass', label: 'Busolă', icon: CompassIcon },
{ key: 'anchor', label: 'Ancoră', icon: AnchorIcon },
{ key: 'flag', label: 'Steag', icon: FlagIcon },
{ key: 'home', label: 'Casă', icon: HomeIcon },
{ key: 'building', label: 'Clădire', icon: BuildingIcon },
{ key: 'briefcase', label: 'Servietă', icon: BriefcaseIcon },
{ key: 'handshake', label: 'Strângere de mână', icon: HandshakeIcon },
{ key: 'users', label: 'Echipă', icon: UsersIcon },
{ key: 'smile', label: 'Zâmbet', icon: SmileIcon },
{ key: 'thumbsUp', label: 'Like', icon: ThumbsUpIcon },
{ key: 'megaphone', label: 'Portavoce', icon: MegaphoneIcon },
{ key: 'message', label: 'Mesaj', icon: MessageCircleIcon },
{ key: 'mail', label: 'Email', icon: MailIcon },
{ key: 'send', label: 'Trimite', icon: SendIcon },
{ key: 'inbox', label: 'Inbox', icon: InboxIcon },
{ key: 'phone', label: 'Telefon', icon: PhoneIcon },
{ key: 'smartphone', label: 'Mobil', icon: SmartphoneIcon },
{ key: 'headphones', label: 'Căști', icon: HeadphonesIcon },
{ key: 'mic', label: 'Microfon', icon: MicIcon },
{ key: 'music', label: 'Muzică', icon: MusicIcon },
{ key: 'video', label: 'Video', icon: VideoIcon },
{ key: 'play', label: 'Play', icon: PlayIcon },
{ key: 'film', label: 'Film', icon: FilmIcon },
{ key: 'camera', label: 'Cameră foto', icon: CameraIcon },
{ key: 'image', label: 'Imagine', icon: ImageIcon },
{ key: 'palette', label: 'Paletă', icon: PaletteIcon },
{ key: 'penTool', label: 'Peniță', icon: PenToolIcon },
{ key: 'presentation', label: 'Prezentare', icon: PresentationIcon },
{ key: 'monitor', label: 'Monitor', icon: MonitorIcon },
{ key: 'laptop', label: 'Laptop', icon: LaptopIcon },
{ key: 'cpu', label: 'Procesor', icon: CpuIcon },
{ key: 'database', label: 'Bază de date', icon: DatabaseIcon },
{ key: 'cloud', label: 'Cloud', icon: CloudIcon },
{ key: 'code', label: 'Cod', icon: CodeIcon },
{ key: 'settings', label: 'Setări', icon: SettingsIcon },
{ key: 'search', label: 'Căutare', icon: SearchIcon },
{ key: 'eye', label: 'Ochi', icon: EyeIcon },
{ key: 'click', label: 'Click', icon: MousePointerClickIcon },
{ key: 'link', label: 'Link', icon: LinkIcon },
{ key: 'paperclip', label: 'Agrafă', icon: PaperclipIcon },
{ key: 'folder', label: 'Folder', icon: FolderIcon },
{ key: 'file', label: 'Document', icon: FileTextIcon },
{ key: 'clipboard', label: 'Listă sarcini', icon: ClipboardListIcon },
{ key: 'listChecks', label: 'Bife', icon: ListChecksIcon },
{ key: 'book', label: 'Carte', icon: BookOpenIcon },
{ key: 'bookmark', label: 'Semn de carte', icon: BookmarkIcon },
{ key: 'graduation', label: 'Absolvire', icon: GraduationCapIcon },
{ key: 'newspaper', label: 'Ziar', icon: NewspaperIcon },
{ key: 'printer', label: 'Imprimantă', icon: PrinterIcon },
{ key: 'download', label: 'Descarcă', icon: DownloadIcon },
{ key: 'layers', label: 'Straturi', icon: LayersIcon },
{ key: 'calendar', label: 'Calendar', icon: CalendarIcon },
{ key: 'clock', label: 'Ceas', icon: ClockIcon },
{ key: 'alarm', label: 'Alarmă', icon: AlarmClockIcon },
{ key: 'timer', label: 'Cronometru', icon: TimerIcon },
{ key: 'bell', label: 'Clopoțel', icon: BellIcon },
{ key: 'info', label: 'Informație', icon: InfoIcon },
{ key: 'alert', label: 'Atenție', icon: AlertTriangleIcon },
{ key: 'lifeBuoy', label: 'Suport', icon: LifeBuoyIcon },
{ key: 'leaf', label: 'Frunză', icon: LeafIcon },
{ key: 'sun', label: 'Soare', icon: SunIcon },
{ key: 'moon', label: 'Lună', icon: MoonIcon },
{ key: 'coffee', label: 'Cafea', icon: CoffeeIcon },
{ key: 'dumbbell', label: 'Ganteră', icon: DumbbellIcon }];


export const elementIcon = (key?: string) =>
elementIconOptions.find((option) => option.key === key) ??
elementIconOptions[0];

/** Randează iconița aleasă la dimensiunea și culoarea cerute */
export function ElementIcon({
  iconKey,
  size,
  color




}: {iconKey?: string;size: number;color: string;}) {
  const option = elementIcon(iconKey);
  const Icon = option.icon;
  return (
    <Icon
      style={{ width: size, height: size, color }}
      fill={option.filled ? color : 'none'}
      aria-hidden="true" />);


}